version: "3.9"
services:
  web:
    container_name: "mtb2020_web" # コンテナ名
    build: .
    ports: # 解放するポート
      - "3000:3000"
      - "8000:8000"
    environment: # 環境変数
      PORT: 8000
    volumes: # ホストマシンとのファイル共有設定
      - ../:/opt/mtb2020:cached
    command: /bin/sh -c "while sleep 1000; do :; done" # コンテナ起動時に実行されるコマンド
