version: "3.9"
services:
  web:
    container_name: "mtb2020_web"
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      PORT: 8000
    depends_on:
      - db
    volumes:
      - ../:/opt/mtb2020:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    container_name: "mtb2020_db"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "npcnpc"
