version: "3.9"
services:
  web:
    container_name: "mtb2020_web"
    build: ../webapp
    ports:
      - "3000:3000"
      - "8000:8000"
    # env_file: .env
    depends_on:
      - db
    volumes:
      - ../:/opt/:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    container_name: "mtb2020_db"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "npcnpc"
