version: "3.9"
services:
  web:
    # コンテナ名
    container_name: "mtb2020_web"
    # 気にしないでOK
    build: .
    # 解放するポート
    ports:
      - "3000:3000"
      - "8000:8000"
    # 環境変数
    environment:
      PORT: 8000
    # ホストマシンとのファイル共有設定
    volumes:
      - ../:/opt/mtb2020:cached
    # コンテナ起動時に実行されるコマンド
    command: /bin/sh -c "while sleep 1000; do :; done"
